function [sld, ax] = SliderPlotSigma(out)

fig = figure("WindowStyle","normal");
ax = axes(fig,"Position",[0.13,0.15,0.775,0.8]);

SIGMA = out.yout(out.ns*out.msh.Nc+1:out.ns*out.msh.Nc+out.msh.Nd,:);
nt = numel(out.tout);

top_lim = max(SIGMA,[],"all");
bottom_lim = min(SIGMA,[],"all");

sld = uicontrol(fig, ...
    'Style','slider', ...
    'Min',1, 'Max',nt, 'Value',1, 'SliderStep',[1/(nt-1),max(0.05,1/(nt-1))],...
    'Units','normalized', ...
    'Visible','on',...
    'Position',[0.2, 0.005, 0.6, 0.03], ...
    'Callback', @(src,~) PlotSigma(round(src.Value)));

lbl_indices = annotation(fig, 'textbox', ...
    [0.005 0.005, 0.19, 0.03], ...   
    'String','', ...
    'FitBoxToText','on', ...
    'EdgeColor','k', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","right",...
    "VerticalAlignment","middle",...
    'FontSize',12);

lbl_time_instant = annotation(fig, 'textbox', ...
    [0.81 0.005, 0.19, 0.03], ...   
    'String','', ...
    'FitBoxToText','on', ...
    'EdgeColor','none', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","left",...
    "VerticalAlignment","bottom",...
    'FontSize',12);

btn = uicontrol(fig, ...
    'Style','togglebutton', ...
    'String','global', ...
    'Units','normalized', ... 
    'Value', 1,...
    'Position',[0.93 0.95 0.06 0.04], ...
    'Callback',@(src,~) PlotSigma(round(sld.Value)));

sigmak = SIGMA(:,1);
x = out.msh.xf(out.msh.f_from_d);
pl = plot(ax, x, sigmak, ".-");
ylabel("surface charge density $(\mathrm{C}\mathrm{m}^{-2})$", "Interpreter","latex")
xlim([min(x), max(x)])
xlabel("x $(\mathrm{m})$", "Interpreter","latex")
grid on
ax.TickLabelInterpreter = "latex";
ax.FontSize = 15;

function PlotSigma(k)
    lbl_indices.String = num2str(k) + " / " + numel(out.tout);
    lbl_time_instant.String = sprintf("t = %.5e s", out.tout(k));
    s_k = SIGMA(:,k);
    pl.YData = s_k;
    if btn.Value == 1
        ylim(ax,[bottom_lim, top_lim])
        btn.String = "global";
    else
        if max(s_k) ~= min(s_k)
            ylim(ax,[min(s_k), max(s_k)])
        else
            ax.YLimMode = "auto";
        end
        btn.String = "auto";
    end
end

end