function [fig,E_txt,Rho_txt,N_txt,O_txt,K_txt,R_txt,popmen_species,popmen_reactions] = InitializeCellInspector(s_names,reactions)
fig = figure("MenuBar","none","Position",[100,100,1000,200],"Resize","off");

annotation(fig,'textbox',[0.01,0.8,0.2,0.1],'String',"Electric Field $(\mathrm{Vm^{-1}}, \mathrm{Td)}$:", ...
    'Interpreter','latex','EdgeColor','none','FontSize',12,"HorizontalAlignment","left");
E_txt = uicontrol(fig,'Style','text', ...
    'String',sprintf("%.3e, %.3e",-5.3655e150,-5.3655e150), ...
    'Units','normalized','Position',[0.2,0.77,0.3,0.1], ...
    'FontSize',12,'HorizontalAlignment','left');

annotation(fig,'textbox',[0.52,0.8,0.17,0.1],'String',"Charge Density $(\mathrm{Cm^{-3}})$:", ...
    'Interpreter','latex','EdgeColor','none','FontSize',12,"HorizontalAlignment","left");
Rho_txt = uicontrol(fig,'Style','text', ...
    'String',sprintf("%.3e",-5.3655e150), ...
    'Units','normalized','Position',[0.7,0.77,0.1,0.1], ...
    'FontSize',12,'HorizontalAlignment','left');

uicontrol(fig,'Style','text', ...
    'String',"Species", ...
    'Units','normalized','Position',[0.01,0.6,0.2,0.1], ...
    'FontSize',10,'HorizontalAlignment','left');
popmen_species = uicontrol(fig, ...
    'Style','popupmenu', ...
    'String',cellstr(s_names), ...
    'Units','normalized', ...
    'Position',[0.01 0.4 0.5 0.2], ...
    'Value',1);

annotation(fig,'textbox',[0.52,0.52,0.1,0.1],'String',"Density $(\mathrm{m^{-3}})$:", ...
    'Interpreter','latex','EdgeColor','none','FontSize',12,"HorizontalAlignment","left");
N_txt = uicontrol(fig,'Style','text', ...
    'String',sprintf("%.3e",-5.3655e150), ...
    'Units','normalized','Position',[0.64,0.49,0.1,0.1], ...
    'FontSize',12,'HorizontalAlignment','left');

annotation(fig,'textbox',[0.77,0.52,0.1,0.1],'String',"Omega $(\mathrm{m^{-3}s^{-1}})$:", ...
    'Interpreter','latex','EdgeColor','none','FontSize',12,"HorizontalAlignment","left");
O_txt = uicontrol(fig,'Style','text', ...
    'String',sprintf("%.3e",-5.3655e150), ...
    'Units','normalized','Position',[0.9,0.49,0.1,0.1], ...
    'FontSize',12,'HorizontalAlignment','left');

uicontrol(fig,'Style','text', ...
    'String',"Reactions", ...
    'Units','normalized','Position',[0.01,0.25,0.2,0.1], ...
    'FontSize',10,'HorizontalAlignment','left');
popmen_reactions = uicontrol(fig, ...
    'Style','popupmenu', ...
    'String',cellstr(reactions), ...
    'Units','normalized', ...
    'Position',[0.01 0.05 0.5 0.2], ...
    'Value',1);

annotation(fig,'textbox',[0.52,0.17,0.2,0.1],'String',"Rate Coeff. $(\mathrm{m^{3}s^{-1}})$:", ...
    'Interpreter','latex','EdgeColor','none','FontSize',12,"HorizontalAlignment","left");
K_txt = uicontrol(fig,'Style','text', ...
    'String',sprintf("%.3e",-5.3655e150), ...
    'Units','normalized','Position',[0.67,0.14,0.1,0.1], ...
    'FontSize',12,'HorizontalAlignment','left');

annotation(fig,'textbox',[0.77,0.17,0.2,0.1],'String',"Rate $(\mathrm{m^{-3}s^{-1}})$:", ...
    'Interpreter','latex','EdgeColor','none','FontSize',12,"HorizontalAlignment","left");
R_txt = uicontrol(fig,'Style','text', ...
    'String',sprintf("%.3e",-5.3655e150), ...
    'Units','normalized','Position',[0.88,0.14,0.1,0.1], ...
    'FontSize',12,'HorizontalAlignment','left');
end