function NewSliderView(out,cell_types)
%SliderView creates a slider to easily navigate over time instants
%   IV
%   Sigma
%   Cell

sld_cell = cell(1, numel(cell_types));
ed_xlim_inf_cell = cell(0);
ed_xlim_sup_cell = cell(0);
ed_ylim_inf_cell = cell(0);
ed_ylim_sup_cell = cell(0);

k = 1;
for ic = 1:numel(cell_types)
    if cell_types{ic} == "Cell"
        [sld_cell{ic}, ed_xlim_inf_cell{k}, ed_xlim_sup_cell{k}, ed_ylim_inf_cell{k}, ed_ylim_sup_cell{k}] = NewSliderPlotCell(out);
        k = k + 1;
    else
        eval("sld_cell{" + ic + "} = SliderPlot" + cell_types{ic} + "(out);")
    end
end

fig = figure("Position",[100, 100, 600, 100], "ToolBar","none", "MenuBar","none", "Resize","off");

lbl_i = annotation(fig, 'textbox', ...
    [0.81 0.4, 0.15, 0.3], ...   
    'String','', ...
    'FitBoxToText','off', ...
    'EdgeColor','k', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","right",...
    "VerticalAlignment","middle",...
    'FontSize',12);

lbl_t = annotation(fig, 'textbox', ...
    [0.4 0.7 0.2 0.2], ...   
    'String','', ...
    'FitBoxToText','on', ...
    'EdgeColor','none', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","center",...
    "VerticalAlignment","bottom",...
    'FontSize',12);

uicontrol(fig, ...
    'Style','slider', ...
    'Min',1, 'Max',numel(out.tout), 'Value',1, 'SliderStep',[1/(numel(out.tout)-1),max(0.05,1/(numel(out.tout)-1))],...
    'Units','normalized', ...
    'Position',[0.04 0.4, 0.76, 0.3], ...
    'Callback', @(src,~) MasterSliderCallBack(round(src.Value)));

ed_xlim_inf_master = uicontrol(fig,"Style","edit","Units","normalized","Position",[0.25,  0.05, 0.1, 0.25]);
ed_xlim_sup_master = uicontrol(fig,"Style","edit","Units","normalized","Position",[0.35,  0.05, 0.1, 0.25]);
ed_ylim_inf_master = uicontrol(fig,"Style","edit","Units","normalized","Position",[0.55, 0.05, 0.1, 0.25]);
ed_ylim_sup_master = uicontrol(fig,"Style","edit","Units","normalized","Position",[0.65, 0.05, 0.1, 0.25]);

annotation(fig, 'textbox', ...
    [0.22 0.05 0.03 0.25], ...   
    'String','x', ...
    'FitBoxToText','off', ...
    'EdgeColor','k', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","center",...
    "VerticalAlignment","bottom",...
    'FontSize',8);

annotation(fig, 'textbox', ...
    [0.52 0.05 0.03 0.25], ...   
    'String','y', ...
    'FitBoxToText','off', ...
    'EdgeColor','k', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","center",...
    "VerticalAlignment","bottom",...
    'FontSize',8);

uicontrol(fig, ...
    'Style','pushbutton', ...
    'String','set all', ...
    'Units','normalized', ... 
    'UserData',0,...
    'Position',[0.11 0.05 0.1 0.25], ...
    'Callback',@(src,~)SetAll);

MasterSliderCallBack(1);

    function MasterSliderCallBack(k)
        lbl_i.String = num2str(k) + " / " + numel(out.tout);
        lbl_t.String = sprintf("t = %.5e s", out.tout(k));
        for i = 1:numel(sld_cell)
            sld_cell{i}.Value = k; feval(sld_cell{i}.Callback, sld_cell{i}, [])
        end
        figure(fig)
    end

    function SetAll
        for i = 1:numel(ed_xlim_inf_cell)
            ed_xlim_inf_cell{i}.String = ed_xlim_inf_master.String;
            ed_xlim_sup_cell{i}.String = ed_xlim_sup_master.String;
            ed_ylim_inf_cell{i}.String = ed_ylim_inf_master.String;
            ed_ylim_sup_cell{i}.String = ed_ylim_sup_master.String;
        end
    end

end
