function SliderView(out_pp,cell_types)

sld_cell = cell(1, numel(cell_types));

for ic = 1:numel(cell_types)
    eval("sld_cell{" + ic + "} = SliderPlot" + cell_types{ic} + "(out_pp);")
end

fig = figure("Position",[100, 100, 600, 100], "ToolBar","none", "MenuBar","none", "Resize","off");

lbl_i = annotation(fig, 'textbox', ...
    [0.81 0.4, 0.15, 0.3], ...   
    'String','', ...
    'FitBoxToText','off', ...
    'EdgeColor','k', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","right",...
    "VerticalAlignment","middle",...
    'FontSize',12);

lbl_t = annotation(fig, 'textbox', ...
    [0.4 0.05 0.2 0.2], ...   
    'String','', ...
    'FitBoxToText','on', ...
    'EdgeColor','none', ...
    'Interpreter','latex', ...
    "HorizontalAlignment","center",...
    "VerticalAlignment","bottom",...
    'FontSize',12);

uicontrol(fig, ...
    'Style','slider', ...
    'Min',1, 'Max',out_pp.nt, 'Value',1, 'SliderStep',[1/(out_pp.nt-1),0.05],...
    'Units','normalized', ...
    'Position',[0.04 0.4, 0.76, 0.3], ...
    'Callback', @(src,~) MasterSliderCallBack(round(src.Value)));

MasterSliderCallBack(1);

function MasterSliderCallBack(k)
    lbl_i.String = num2str(k) + " / " + out_pp.nt;
    lbl_t.String = sprintf("t = %.5e s", out_pp.tout(k));
    for i = 1:numel(sld_cell)
        sld_cell{i}.Value = k; feval(sld_cell{i}.Callback, sld_cell{i}, [])
    end
    figure(fig)
end

end
